"use client";
import { useMemo, useState } from "react";

type Product={id:string;name:string;price:number;category:string;description:string;image:string;custom?:boolean;badge?:string};
type CartItem=Product&{qty:number;extras:string[];premium:string[];cutlery:string};
const products:Product[]=[
 {id:"550",name:"Açaí 550ml",price:24,category:"Açaí",description:"Até 8 adicionais grátis",custom:true,badge:"Mais pedido",image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202504031504_715X_blob"},
 {id:"casal",name:"Combo casal • 2× 550ml",price:40.48,category:"Combos",description:"Dois copos iguais para dividir",custom:true,badge:"12% OFF",image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202504031513_80HQ_blob"},
 {id:"330",name:"Açaí 330ml",price:18,category:"Açaí",description:"Até 8 adicionais grátis",custom:true,image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202504031434_H811_blob"},
 {id:"440",name:"Açaí 440ml",price:22,category:"Açaí",description:"Até 8 adicionais grátis",custom:true,image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202504031501_219T_blob"},
 {id:"770",name:"Açaí 770ml",price:32,category:"Açaí",description:"Até 8 adicionais grátis",custom:true,image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202504031509_ULFD_blob"},
 {id:"1l",name:"Açaí 1 litro",price:48,category:"Açaí",description:"Tamanho família, adicionais grátis",custom:true,image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202505102323_XQB1_blob"},
 {id:"especial",name:"Especial Nutella + Ninho",price:35,category:"Copos prontos",description:"550ml com Nutella e creme de Ninho",image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202506111947_0054_blob"},
 {id:"shake",name:"Milk-shake Ferrero Rocher",price:22.5,category:"Milk-shakes",description:"500ml cremoso e refrescante",badge:"10% OFF",image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202604141715_LB07_iblob"},
 {id:"sorvete",name:"Sorvete Ferrero Rocher",price:17,category:"Sorvetes",description:"300ml com 3 bolas",image:"https://client-assets.anota.ai/produtos/6876f462629ff00019fb2856/202604141629_1KF1_iblob"}
];
const free=["Amendoim","Banana","Morango","Chocoball","Confete","Granola","Granulado","Leite condensado","Leite em pó","Ovomaltine","Paçoca","Mousse de Maracujá","Mousse de Morango"];
const premium=[["Paçoquê",3],["Choco-Malte",4],["Creme de Ninho",3.5],["Nutella",4]] as const;
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function Store(){
 const [category,setCategory]=useState("Todos"); const [builder,setBuilder]=useState<Product|null>(null); const [extras,setExtras]=useState<string[]>([]); const [prem,setPrem]=useState<string[]>([]); const [cutlery,setCutlery]=useState("Sem talher"); const [cart,setCart]=useState<CartItem[]>([]); const [cartOpen,setCartOpen]=useState(false); const [checkout,setCheckout]=useState(false); const [notice,setNotice]=useState("");
 const categories=["Todos","Açaí","Combos","Copos prontos","Milk-shakes","Sorvetes"]; const shown=category==="Todos"?products:products.filter(p=>p.category===category);
 const total=useMemo(()=>cart.reduce((s,i)=>s+(i.price+i.premium.reduce((a,n)=>a+(premium.find(p=>p[0]===n)?.[1]||0),0))*i.qty,0),[cart]);
 const toggle=(name:string,list:string[],set:(v:string[])=>void,max=99)=>set(list.includes(name)?list.filter(x=>x!==name):list.length<max?[...list,name]:list);
 const open=(p:Product)=>{if(p.custom){setBuilder(p);setExtras([]);setPrem([]);setCutlery("Sem talher")}else add(p,[],[],"Sem talher")};
 const add=(p:Product,e:string[],pr:string[],c:string)=>{setCart(v=>[...v,{...p,qty:1,extras:e,premium:pr,cutlery:c}]);setBuilder(null);setCartOpen(true)};
 const changeQty=(i:number,d:number)=>setCart(v=>v.map((x,n)=>n===i?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 async function pay(ev:React.FormEvent<HTMLFormElement>){ev.preventDefault();setNotice("Preparando seu pagamento seguro…");const fd=new FormData(ev.currentTarget);try{const res=await fetch("/api/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customer:{name:fd.get("name"),phone:fd.get("phone"),address:fd.get("address")},cart:cart.map(i=>({id:i.id,qty:i.qty,premium:i.premium,extras:i.extras,cutlery:i.cutlery}))})});const data=await res.json() as {url?:string;error?:string};if(!res.ok||!data.url)throw new Error(data.error||"Não foi possível iniciar o pagamento.");window.location.href=data.url}catch(err){setNotice(err instanceof Error?err.message:"Não foi possível iniciar o pagamento.")}}
 return <main>
  <header className="top"><div className="store-shell nav2"><a className="logo" href="#"><span>A</span><b>Açaí 24 horas</b></a><nav><a href="#cardapio">Cardápio</a><a href="#como">Como funciona</a><a href="https://instagram.com/acai24horas.pn">Instagram</a></nav><div className="open-pill"><i/> Aberto até 23h59</div><button className="cart-btn" onClick={()=>setCartOpen(true)}>Sacola <span>{cart.reduce((s,i)=>s+i.qty,0)}</span></button></div></header>
  <section className="hero2"><div className="store-shell hero2-grid"><div><div className="micro">DELIVERY ATÉ MEIA-NOITE • PEDIDO MÍNIMO R$ 14</div><h1>Monte seu açaí.<br/><em>Do seu jeito.</em></h1><p>Escolha o tamanho, combine até 8 adicionais grátis e receba a felicidade em forma de açaí.</p><a className="primary" href="#cardapio">Começar meu pedido <span>↓</span></a><div className="proof"><b>4.9 ★</b><span>Mais de 150 clientes satisfeitos</span></div></div><div className="hero-product"><div className="sun"/><img src={products[0].image} alt="Açaí 550ml com frutas e acompanhamentos"/><div className="float f1"><small>A partir de</small><b>R$ 18</b></div><div className="float f2"><b>8 adicionais</b><small>grátis para escolher</small></div></div></div></section>
  <section className="promise"><div className="store-shell"><span>✦ Açaí cremoso</span><span>✦ Adicionais grátis</span><span>✦ Entrega rápida</span><span>✦ Pagamento seguro</span></div></section>
  <section className="catalog" id="cardapio"><div className="store-shell"><div className="section-title"><div><small>ESCOLHA SEU FAVORITO</small><h2>O que vai pedir hoje?</h2></div><div className="search">⌕ <input aria-label="Buscar no cardápio" placeholder="Buscar no cardápio"/></div></div><div className="tabs">{categories.map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="product-grid">{shown.map(p=><article className="product" key={p.id}>{p.badge&&<span className="badge">{p.badge}</span>}<div className="photo"><img src={p.image} alt={p.name}/></div><div className="product-body"><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><div><b>{money(p.price)}</b><button onClick={()=>open(p)} aria-label={`Adicionar ${p.name}`}>+</button></div></div></article>)}</div></div></section>
  <section className="how" id="como"><div className="store-shell"><div><small>SEM COMPLICAÇÃO</small><h2>Seu açaí em<br/>três passos.</h2></div>{[["01","Escolha o tamanho","Do 330ml ao 1 litro."],["02","Monte como quiser","Até 8 adicionais grátis."],["03","Receba em casa","Finalize e acompanhe seu pedido."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <footer><div className="store-shell"><a className="logo" href="#"><span>A</span><b>Açaí 24 horas</b></a><p>Seu açaí, suas escolhas, sua melhor hora.</p><a href="https://instagram.com/acai24horas.pn">@acai24horas.pn ↗</a></div></footer>

  {builder&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setBuilder(null)}><section className="builder" role="dialog" aria-modal="true" aria-label={`Montar ${builder.name}`}><button className="close" onClick={()=>setBuilder(null)}>×</button><div className="builder-head"><img src={builder.image} alt=""/><div><small>MONTE DO SEU JEITO</small><h2>{builder.name}</h2><p>{money(builder.price)} • até 8 adicionais grátis</p></div></div><div className="builder-scroll"><h3>1. Escolha seus adicionais <span>{extras.length}/8</span></h3><p>Selecione até 8 opções grátis.</p><div className="choices">{free.map(x=><button className={extras.includes(x)?"selected":""} onClick={()=>toggle(x,extras,setExtras,8)} key={x}><span>{extras.includes(x)?"✓":"+"}</span>{x}</button>)}</div><h3>2. Quer turbinar? <span>opcional</span></h3><div className="choices premium">{premium.map(([x,v])=><button className={prem.includes(x)?"selected":""} onClick={()=>toggle(x,prem,setPrem)} key={x}><span>{prem.includes(x)?"✓":"+"}</span><b>{x}</b><em>+ {money(v)}</em></button>)}</div><h3>3. Precisa de talher?</h3><div className="cutlery">{["Quero talher","Sem talher"].map(x=><button className={cutlery===x?"selected":""} onClick={()=>setCutlery(x)} key={x}>{cutlery===x?"●":"○"} {x}</button>)}</div></div><div className="builder-foot"><div><small>Total</small><b>{money(builder.price+prem.reduce((s,x)=>s+(premium.find(p=>p[0]===x)?.[1]||0),0))}</b></div><button className="primary" onClick={()=>add(builder,extras,prem,cutlery)}>Adicionar à sacola <span>→</span></button></div></section></div>}
  {cartOpen&&<div className="overlay right" onMouseDown={e=>e.target===e.currentTarget&&setCartOpen(false)}><aside className="cart"><button className="close" onClick={()=>setCartOpen(false)}>×</button><h2>Sua sacola <span>{cart.length}</span></h2>{cart.length===0?<div className="empty"><b>♡</b><h3>Sua sacola está vazia</h3><p>Escolha seu açaí favorito para começar.</p><button className="primary" onClick={()=>setCartOpen(false)}>Ver cardápio</button></div>:<><div className="cart-items">{cart.map((i,n)=><article key={n}><img src={i.image} alt=""/><div><h3>{i.name}</h3><p>{[...i.extras,...i.premium].join(", ")||"Sem adicionais"}</p><b>{money(i.price+i.premium.reduce((s,x)=>s+(premium.find(p=>p[0]===x)?.[1]||0),0))}</b></div><div className="qty"><button onClick={()=>changeQty(n,-1)}>−</button><span>{i.qty}</span><button onClick={()=>changeQty(n,1)}>+</button></div></article>)}</div><div className="cart-total"><p><span>Subtotal</span><b>{money(total)}</b></p><small>Taxa de entrega calculada no checkout</small><button className="primary" onClick={()=>{setCartOpen(false);setCheckout(true)}} disabled={total<14}>Continuar para pagamento <span>→</span></button>{total<14&&<em>O pedido mínimo é R$ 14,00</em>}</div></>}</aside></div>}
  {checkout&&<div className="overlay"><section className="checkout" role="dialog" aria-modal="true"><button className="close" onClick={()=>setCheckout(false)}>×</button><div><small>ÚLTIMO PASSO</small><h2>Entrega e pagamento</h2></div><form onSubmit={pay}><label>Nome completo<input name="name" required placeholder="Seu nome"/></label><label>WhatsApp<input name="phone" required inputMode="tel" placeholder="(00) 00000-0000"/></label><label className="wide">Endereço de entrega<input name="address" required placeholder="Rua, número e bairro"/></label><fieldset className="wide"><legend>Como quer pagar?</legend><label><input type="radio" name="payment" defaultChecked/> <span>▣</span> Pix <small>Aprovação imediata</small></label><label><input type="radio" name="payment"/> <span>▤</span> Cartão <small>Crédito ou débito</small></label></fieldset>{notice&&<p className="notice wide">{notice}</p>}<div className="checkout-total wide"><span>Total do pedido</span><b>{money(total)}</b></div><button className="primary wide" type="submit">Pagar com segurança <span>→</span></button></form><small className="secure">🔒 Seus dados de pagamento são protegidos e não ficam armazenados.</small></section></div>}
 </main>
}
