const whatsapp = "https://wa.me/5511987654321?text=Ol%C3%A1%21%20Quero%20fazer%20meu%20pedido%20de%20a%C3%A7a%C3%AD.";
const services=[{title:"Açaí personalizado",text:"Monte seu copo com os acompanhamentos que você mais ama."},{title:"Combos especiais",text:"Combinações equilibradas, saborosas e prontas para pedir."},{title:"Entrega rápida",text:"Seu pedido preparado na hora e enviado com todo cuidado."}];
const reviews=[{name:"Mariana Silva",text:"Atendimento impecável! O ambiente é super acolhedor e a equipe é muito profissional. Recomendo de olhos fechados."},{name:"Carlos Eduardo Santos",text:"Melhor experiência da região. Pontualidade, transparência e qualidade excepcional em cada detalhe."},{name:"Fernanda Oliveira",text:"Superou todas as expectativas. Já virei cliente fiel e indico para todos os meus amigos e familiares!"}];

export default function Home() {
  return (
    <main>
      <nav className="nav shell" aria-label="Navegação principal">
        <a className="brand" href="#inicio" aria-label="Açaí 24 horas Pn — início"><span className="brand-mark">A</span><span>Açaí <b>24h</b> Pn</span></a>
        <div className="nav-links"><a href="#sobre">Sobre</a><a href="#servicos">Cardápio</a><a href="#depoimentos">Avaliações</a><a href="#localizacao">Localização</a></div>
        <a className="button button-small" href={whatsapp}>Pedir agora <span>↗</span></a>
      </nav>
      <section className="hero shell" id="inicio">
        <div className="hero-copy">
          <div className="eyebrow"><span className="pulse" /> Aberto hoje até às 19h</div>
          <h1>Seu açaí favorito,<br /><em>do seu jeito.</em></h1>
          <p>Fresco, cremoso e preparado na hora. Monte sua combinação perfeita e receba onde estiver.</p>
          <div className="hero-actions"><a className="button" href={whatsapp}>Quero pedir no WhatsApp <span>↗</span></a><a className="text-link" href="#servicos">Ver nosso cardápio <span>↓</span></a></div>
          <div className="social-proof"><div className="faces" aria-hidden="true"><span>MS</span><span>CE</span><span>FO</span></div><div><div className="stars">★★★★★</div><strong>4.9 no Google</strong> <small>• 156 avaliações</small></div></div>
        </div>
        <div className="hero-visual" aria-label="Tigela de açaí com frutas e granola">
          <div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="berry berry-one" /><div className="berry berry-two" /><div className="berry berry-three" />
          <div className="bowl"><div className="acai"><span className="banana b1" /><span className="banana b2" /><span className="banana b3" /><span className="banana b4" /><span className="strawberry">◆</span><span className="granola">● · ● · · ● · ●</span></div></div>
          <div className="floating-card"><span className="check">✓</span><div><strong>Feito na hora</strong><small>Ingredientes frescos</small></div></div>
        </div>
      </section>
      <div className="trust-strip"><div className="shell"><span>✦ Açaí selecionado</span><span>✦ Ingredientes frescos</span><span>✦ Atendimento acolhedor</span><span>✦ Peça pelo WhatsApp</span></div></div>
      <section className="section light" id="sobre"><div className="shell split"><div className="visual-card"><span>AÇAÍ<br/><b>24h</b></span><aside><b>4.9 ★</b><small>156 avaliações</small></aside></div><div><span className="kicker">NOSSA ESSÊNCIA</span><h2>Sabor que aproxima.<br/><em>Cuidado que conquista.</em></h2><p className="lead">Cada pedido é uma oportunidade de criar uma experiência especial. Unimos ingredientes selecionados, preparo cuidadoso e atendimento próximo para entregar muito mais que um açaí.</p><ul className="checks"><li>Preparo cuidadoso em cada detalhe</li><li>Atendimento personalizado e acolhedor</li><li>Qualidade desde a primeira colherada</li></ul><a className="underlink" href="https://instagram.com/acai24horas.pn">Conheça nossa história no Instagram ↗</a></div></div></section>
      <section className="section sand" id="servicos"><div className="shell"><div className="section-head"><div><span className="kicker">FEITO PARA VOCÊ</span><h2>Escolha, combine<br/>e <em>aproveite.</em></h2></div><p className="lead">Tem uma opção perfeita para cada momento do seu dia. Escolha a sua e faça o pedido em poucos cliques.</p></div><div className="cards">{services.map((s,i)=><article className="card" key={s.title}><small>0{i+1}</small><i>{i===0?"✦":i===1?"●":"◆"}</i><h3>{s.title}</h3><p>{s.text}</p><a href={whatsapp}>Quero este <b>→</b></a></article>)}</div></div></section>
      <section className="section wine"><div className="shell split benefits"><div><span className="kicker yellow">POR QUE ESCOLHER A GENTE</span><h2>O cuidado está<br/>em <em>cada detalhe.</em></h2></div><div className="benefit-grid"><article><b>01</b><h3>Atendimento humanizado</h3><p>A gente escuta e prepara cada pedido com atenção de verdade.</p></article><article><b>02</b><h3>Qualidade garantida</h3><p>Ingredientes selecionados, textura e frescor consistentes.</p></article><article><b>03</b><h3>Agilidade no preparo</h3><p>Seu açaí gostoso e no tempo certo.</p></article><article><b>04</b><h3>Confiança comprovada</h3><p>Nota 4.9 no Google por 156 clientes.</p></article></div></div></section>
      <section className="section light" id="depoimentos"><div className="shell"><div className="center"><span className="kicker">QUEM PROVA, RECOMENDA</span><h2>Experiências que<br/><em>falam por nós.</em></h2><div className="rating"><b>4.9</b><span>★★★★★<small>156 avaliações no Google</small></span></div></div><div className="cards reviews">{reviews.map((r,i)=><article className="review" key={r.name}><div className="stars">★★★★★</div><p>“{r.text}”</p><footer><span>{["MS","CE","FO"][i]}</span><div><b>{r.name}</b><small>Cliente verificada no Google</small></div></footer></article>)}</div></div></section>
      <section className="section gallery light"><div className="shell"><div className="section-head"><div><span className="kicker">DÁ ÁGUA NA BOCA</span><h2>Feito com carinho.<br/><em>Servido com sabor.</em></h2></div><a className="underlink" href="https://instagram.com/acai24horas.pn">@acai24horas.pn ↗</a></div><div className="gallery-grid"><div><span>Açaí cremoso</span></div><div><span>Frutas frescas</span></div><div><span>Combinações únicas</span></div></div></div></section>
      <section className="section location" id="localizacao"><div className="shell split"><div><span className="kicker yellow">VENHA NOS VISITAR</span><h2>Seu próximo açaí<br/>está <em>bem aqui.</em></h2><div className="info"><b>⌖ Endereço</b><p>Av. Paulista, 1000 - Bela Vista<br/>São Paulo - SP, 01310-100</p><a href="https://maps.google.com/?q=A%C3%A7ai%2024%20horas%20Pn">Abrir no Google Maps ↗</a></div><div className="hours"><p><b>Segunda a sexta</b><span>08:00 – 19:00</span></p><p><b>Sábado</b><span>08:30 – 15:00</span></p><p><b>Domingo</b><span>Fechado</span></p></div></div><div className="map"><div><span>A</span></div><h3>Açai 24 horas Pn</h3><small>Av. Paulista, 1000</small><a className="button" href={whatsapp}>Fazer meu pedido <span>↗</span></a></div></div></section>
      <section className="section light"><div className="shell faq"><div><span className="kicker">DÚVIDAS FREQUENTES</span><h2>Tudo o que você<br/>precisa <em>saber.</em></h2><p className="lead">Ainda ficou com alguma dúvida? Fale com a gente pelo WhatsApp.</p></div><div>{[["Como faço meu pedido?","Clique em um botão amarelo para falar diretamente com nossa equipe no WhatsApp."],["Posso personalizar meu açaí?","Sim. Escolha o tamanho e combine os acompanhamentos disponíveis."],["Vocês fazem entrega?","Sim. Consulte disponibilidade e prazo para seu endereço pelo WhatsApp."],["Quais formas de pagamento aceitam?","Confirme as opções com nossa equipe no momento do pedido."],["Funcionam aos domingos?","Aos domingos estamos fechados. Atendemos de segunda a sábado."]].map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
      <section className="final"><div className="shell"><small>PRONTO PARA PROVAR?</small><h2>Seu açaí perfeito<br/>está a <em>um clique.</em></h2><p>Faça seu pedido agora e descubra por que somos nota 4.9 no Google.</p><a className="button dark" href={whatsapp}>Quero pedir no WhatsApp <span>↗</span></a></div></section>
      <footer><div className="shell footer-grid"><a className="brand" href="#inicio"><span className="brand-mark">A</span><span>Açaí <b>24h</b> Pn</span></a><p>Açaí fresco, atendimento acolhedor<br/>e uma experiência feita para você.</p><nav><a href="#sobre">Sobre</a><a href="#servicos">Cardápio</a><a href="#depoimentos">Avaliações</a><a href="#localizacao">Localização</a></nav><nav><a href="https://instagram.com/acai24horas.pn">Instagram ↗</a><a href={whatsapp}>WhatsApp ↗</a></nav></div><div className="shell copyright"><span>© 2026 Açai 24 horas Pn. Todos os direitos reservados.</span><a href="https://www.aai24horaspn.com.br">www.aai24horaspn.com.br</a></div></footer>
      <a className="wa" href={whatsapp} aria-label="Fazer pedido no WhatsApp">✆</a>
    </main>
  );
}
